export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR'

export const GET_SYMPTOMS_REQUEST = 'GET_SYMPTOMS_REQUEST'
export const GET_SYMPTOMS_SUCCESS = 'GET_SYMPTOMS_SUCCESS'
export const GET_SYMPTOMS_ERROR = 'GET_SYMPTOMS_ERROR'
